### PR TITLE
Add footer to base_layout.html

### PR DESCRIPTION
**Pull request by dvtyga**
added footer code to base_layout

### CODE REVIEW

**Comment by dvtiend** [comment]
looks good for a footer!

**Comment by dvtyga** [comment]
@dvtiend Can you working something on the styling of the footer. I made it quickly but it looks ugly. thanks!

**Comment by dvtiend** [comment]
@dvtiend On it!

**Comment by dvtyga** [comment]
loving the styling! Thanks!

**Comment by dvtiend** [comment]
merging the pull request then.

**Pull request merged**
